# src/HytaleModInstaller/config.py
from __future__ import annotations
import argparse
import os
from pathlib import Path
from platformdirs import user_config_dir
import tomllib


APP_NAME = "hytalemodinstaller"

DEFAULT_STAGING_DIR = Path.home() / "Downloads" / "HytaleMods"
DEFAULT_MODS_DIR = (
        Path.home()
        / ".var/app/com.hypixel.HytaleLauncher/data/Hytale/UserData/Mods"
)


def default_config_path() -> Path:
    return Path(user_config_dir(APP_NAME)) / "config.toml"


def load_user_config(config_path: Path) -> dict:
    if not config_path.is_file():
        return {}
    with config_path.open("rb") as f:
        data = tomllib.load(f)
    return data if isinstance(data, dict) else {}


def write_user_config(config_path: Path, *, staging_dir: Path, mods_dir: Path) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    text = (
        "# Generated by hytalemodinstaller --install\n"
        f'staging_dir = "{staging_dir.as_posix()}"\n'
        f'mods_dir = "{mods_dir.as_posix()}"\n'
    )
    config_path.write_text(text, encoding="utf-8")


def _prompt_path(prompt: str, default: Path) -> Path:
    raw = input(f"{prompt} [{default}]: ").strip()
    chosen = default if raw == "" else Path(raw).expanduser()
    return chosen


def run_install_wizard(config_path: Path) -> None:
    print(f"This will write config to: {config_path}")
    print("Press Enter to accept defaults.\n")

    staging_dir = _prompt_path("Staging directory (watched folder)", DEFAULT_STAGING_DIR)
    mods_dir = _prompt_path("Hytale Mods directory (install target)", DEFAULT_MODS_DIR)

    staging_dir = staging_dir.expanduser()
    mods_dir = mods_dir.expanduser()

    write_user_config(config_path, staging_dir=staging_dir, mods_dir=mods_dir)

    print("\nSaved configuration.")
    print(f"  staging_dir: {staging_dir}")
    print(f"  mods_dir:    {mods_dir}")
    print(f"Config file: {config_path}")


def resolve_paths(args: argparse.Namespace, *, config_path: Path) -> tuple[Path, Path, Path, Path]:
    """
    Precedence (high -> low):
      CLI args > env vars > config.toml

    Policy:
      - If config file does NOT exist (and not running --install), require BOTH dirs
        via args or env vars (no implicit defaults).
      - If config exists, it must contain BOTH keys unless overridden.
    """
    config_exists = config_path.is_file()
    cfg = load_user_config(config_path) if config_exists else {}

    staging_val = cfg.get("staging_dir")
    mods_val = cfg.get("mods_dir")

    staging_env = os.getenv("HYTALEMODINSTALLER_STAGING_DIR")
    mods_env = os.getenv("HYTALEMODINSTALLER_MODS_DIR")
    if staging_env:
        staging_val = staging_env
    if mods_env:
        mods_val = mods_env

    if getattr(args, "staging_dir", None):
        staging_val = args.staging_dir
    if getattr(args, "mods_dir", None):
        mods_val = args.mods_dir

    if not config_exists:
        if not staging_val or not mods_val:
            raise SystemExit(
                "No config file found. Provide BOTH --staging-dir and --mods-dir "
                "(or set HYTALEMODINSTALLER_STAGING_DIR and HYTALEMODINSTALLER_MODS_DIR), "
                "or run with --install."
            )

    if config_exists and (not staging_val or not mods_val):
        raise SystemExit(
            f"Config file is missing required keys. Expected 'staging_dir' and 'mods_dir' in: {config_path}"
        )

    staging_dir = Path(staging_val).expanduser()
    mods_dir = Path(mods_val).expanduser()

    archive_dir = staging_dir / "installed"
    failed_dir = staging_dir / "failed"
    return staging_dir, mods_dir, archive_dir, failed_dir